### ISSUE TITLE
Connecting not possible: 

### ISSUE THREAD

**Issue by chrisw14** [imixs/imixs-admin#53]
I downloaded imixs-admin.war and deployed the war file on the Wildfly 17 server.
Imixs-workflow-5.1.7 is running but I'm not able to connect with imixs-admin  v5.1.2:

![grafik](https://user-images.githubusercontent.com/29482633/72218415-ca804280-353a-11ea-8f39-54f0a61564d7.png)

The API-URL http://localhost:8080/workflow/api is correct. No warning in the log file.

**Comment by chrisw14** [comment]
@rsoika Any updates to this topic? I still have the problem that I can't connect to my API...
Thank you!

**Comment by rsoika** [comment]
Are your application and the admin client running on the same app-server instance? I ask this because the admin-client must be able to reach your application via http connection. In your case 'localhost:8080/worklfow/' ?

The second question is - you are using a form based authentication and not a basic authentication - right?

The third question - you state the API-URL is correct. This means you can type this URL into a new browser window and a form-based login dialog appears? 

Last question - you have really no sever log messages?

**Comment by chrisw14** [comment]
It's running on the same Wildfly server - is this a answer to your question?
![grafik](https://user-images.githubusercontent.com/29482633/77250350-bf871400-6c47-11ea-9bc9-c881936ca3dd.png)

My application url is: localhost:8080/workflow/
The api url is: localhost:8080/workflow/api/
There, I can't see a form login but only:
![grafik](https://user-images.githubusercontent.com/29482633/77250375-ea716800-6c47-11ea-8cc9-c0e08cd35f26.png)

There are really no logs available in the console or in server.log
Thank you

**Comment by rsoika** [comment]
ok, running both apps on one instance of wildfly is fine. But if your application is not working in the browser the admin client will also not be able to connect. 
The browser output of the root api call should print the following:

```
<div class="root">
<a href="/documents" type="application/xml" rel="documents"/>
<a href="/workflow" type="application/xml" rel="workflow"/>
<a href="/model" type="application/xml" rel="model"/>
<a href="/report" type="application/xml" rel="report"/>
<a href="/adminp" type="application/xml" rel="adminp"/>
</div>
```

How does your web.xml security setup look like? Which resources are protected and how is the form based login configured?
This is a typical example:

```
	<!-- Login Module - Formbased-Login  -->
	 <login-config> 
	 	<auth-method>FORM</auth-method> 
		<realm-name>my-realm</realm-name> 
		<form-login-config> 
			<form-login-page>/login.jsf</form-login-page> 
			<form-error-page>/loginerror.jsf</form-error-page> 
		</form-login-config> 
	</login-config> 
	
	
	<!-- Security Roles -->
	<security-constraint>
		<web-resource-collection>
			<web-resource-name>AUTHENTICATED_RESOURCE</web-resource-name>
			<url-pattern>/pages/*</url-pattern>
			<url-pattern>/api/workflow/*</url-pattern>
			<url-pattern>/api/model/*</url-pattern>
			<url-pattern>/api/documents/*</url-pattern>
			<url-pattern>/api/report/*</url-pattern>
			<url-pattern>/api/snapshot/*</url-pattern>
			<url-pattern>/api/adminp/*</url-pattern>
			<!-- exclude /api/metrics -->
		</web-resource-collection>
		<auth-constraint>
			<role-name>org.imixs.ACCESSLEVEL.READERACCESS</role-name>
			<role-name>org.imixs.ACCESSLEVEL.AUTHORACCESS</role-name>
			<role-name>org.imixs.ACCESSLEVEL.EDITORACCESS</role-name>
			<role-name>org.imixs.ACCESSLEVEL.MANAGERACCESS</role-name>
		</auth-constraint>
	</security-constraint>
	<security-role>
		<role-name>org.imixs.ACCESSLEVEL.NOACCESS</role-name>
	</security-role>
	<security-role>
		<role-name>org.imixs.ACCESSLEVEL.READERACCESS</role-name>
	</security-role>
	<security-role>
		<role-name>org.imixs.ACCESSLEVEL.AUTHORACCESS</role-name>
	</security-role>
	<security-role>
		<role-name>org.imixs.ACCESSLEVEL.EDITORACCESS</role-name>
	</security-role>
	<security-role>
		<role-name>org.imixs.ACCESSLEVEL.MANAGERACCESS</role-name>
	</security-role>
```

**Comment by chrisw14** [comment]
Okay, my web.xml looks like this (I added the /api/, that I can see the login form now):

```
  <login-config>
    <auth-method>FORM</auth-method>
    <realm-name>imixsrealm</realm-name>
    <form-login-config>
      <form-login-page>/login.xhtml</form-login-page>
      <form-error-page>/login.xhtml?loginFailed=true</form-error-page>
    </form-login-config>
  </login-config>
  <security-constraint>
    <web-resource-collection>
      <web-resource-name>Auth</web-resource-name>
      <description>application security constraints</description>
	  <url-pattern>/api/*</url-pattern>
      <url-pattern>/applications/*</url-pattern>
      <url-pattern>/index.xhtml</url-pattern>
      <http-method>GET</http-method>
      <http-method>POST</http-method>
      <http-method>PUT</http-method>
      <http-method>DELETE</http-method>
    </web-resource-collection>
    <auth-constraint>
      <role-name>org.imixs.ACCESSLEVEL.READERACCESS</role-name>
      <role-name>org.imixs.ACCESSLEVEL.AUTHORACCESS</role-name>
      <role-name>org.imixs.ACCESSLEVEL.EDITORACCESS</role-name>
      <role-name>org.imixs.ACCESSLEVEL.MANAGERACCESS</role-name>
    </auth-constraint>
  </security-constraint>
  <security-role>
    <role-name>org.imixs.ACCESSLEVEL.NOACCESS</role-name>
  </security-role>
  <security-role>
    <role-name>org.imixs.ACCESSLEVEL.READERACCESS</role-name>
  </security-role>
  <security-role>
    <role-name>org.imixs.ACCESSLEVEL.AUTHORACCESS</role-name>
  </security-role>
  <security-role>
    <role-name>org.imixs.ACCESSLEVEL.EDITORACCESS</role-name>
  </security-role>
  <security-role>
    <role-name>org.imixs.ACCESSLEVEL.MANAGERACCESS</role-name>
  </security-role>
```

**Comment by chrisw14** [comment]
Is it okay that my RestService.java looks like this?

```
import javax.ws.rs.core.Application;

@ApplicationPath("/api")
public class RestService extends Application {
	
	@Inject
	DocumentService documentService;
	
	@Inject
	DocumentRestService documentRestService;
}
```

**Comment by rsoika** [comment]
Yes. Injecting DocumentService and DocumentRestService should not be necessary. An empty class is fine. I wonder if this could have a side effect...?

Is your application in general working? 
If you login into your application are you than able to call the following resource?

    /api/model

This should result in an overview about available models.

**Comment by rsoika** [comment]
At the end it is a javaScript problem within the Imixs-Admin app. You can see the problem in more detail if you activate your browser Developer Mode and watch the javaScript console output. Also the network traffic is interesting here. 

I guess your admin client can not reach your web application on the hostname 'localhost'. 

Can you give more information about your environment? So far I am just guessing that you are running a Wildfly Server on your local dev-machine? Or are there any Docker Containers, VMs or Remote Hosts in the game? Have you tried http://127.0.0.1 instead of localhost?

**Comment by rsoika** [comment]
Also cookies can be a problem here. Try to start the Imixs-Admin client from a different browser or in a private window so that  JSESSION cookies will not conflict.

**Comment by chrisw14** [comment]
Thank you for these hints!

The logs of the JavaScript console are:
```
...imixs-admin started imixs-admin.js:58:15
...connecting '/api/connect'... imixs-admin.js:79:15
404 imixs-admin.js:105:33
Not Found imixs-admin.js:106:33
```

In the network analyis I could found this:
![grafik](https://user-images.githubusercontent.com/29482633/77356201-2854b600-6d46-11ea-945e-80377243ac6e.png)

... and this is of course true, because localhost:8080/api/connect doesn't exist.
It should be localhost:8080/**workflow**/api/connect, I think.

**Comment by rsoika** [comment]
Yes you are totally right. This is a general bug in the [imixs-admin.js library](https://github.com/imixs/imixs-admin/blob/master/src/main/webapp/imixs-admin.js).

We need to fix this.

**Comment by rsoika** [comment]
Just to make it more clear to mee - your Imixs-Admin client runs at

    http://localhost:8080/

Is this correct? It is not running at 

    http://localhost:8080/imixs-admin/    

? (or some other custom root context)

**Comment by rsoika** [comment]
You can download a new version from here:

https://github.com/imixs/imixs-admin/tree/master/src/docker/apps

I guess now that you change the root context of the imixs-admin client when your manually deploy it on wildfly - right?

I think this new version should fix the bug. Let me know if it works

**Comment by chrisw14** [comment]
Yeah, i changed the root-conext to localhost:8080/app/
But now it works perfect. Thank you!
